# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shareit < Formula
  desc ""
  homepage "https://github.com/Njorda/homebrew-tools"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Njorda/homebrew-tools/releases/download/v0.0.13/homebrew-tools_0.0.13_darwin_amd64.tar.gz"
      sha256 "b921a8bb327d89da4a2796cfaa8a7f29c1f780940f4ce4e356f0a885705b721f"

      def install
        bin.install "homebrew-tools"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Njorda/homebrew-tools/releases/download/v0.0.13/homebrew-tools_0.0.13_darwin_arm64.tar.gz"
      sha256 "71f6d7024f2cce6653fd17393f29a589b5f69714ea84008023d06874a72ed4b2"

      def install
        bin.install "homebrew-tools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Njorda/homebrew-tools/releases/download/v0.0.13/homebrew-tools_0.0.13_linux_amd64.tar.gz"
      sha256 "d65671e14c300dabc0ed3e72ad028f0e3495916950c587929bb5b2d5e00d1f23"

      def install
        bin.install "homebrew-tools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Njorda/homebrew-tools/releases/download/v0.0.13/homebrew-tools_0.0.13_linux_arm64.tar.gz"
      sha256 "52619f55f062000e51c520280ded8f3caa7b0629d8ae488a1b152e9835069d96"

      def install
        bin.install "homebrew-tools"
      end
    end
  end
end
